
      <div  id='fuss' >
        <hr>
        <p>Copyright © MCG Version:10.10.2021 </p>
      </div>
    </div>
  </div>

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-pprn3073KE6tl6bjs2QrFaJGz5/SUsLqktiwsUTF55Jfv3qYSDhgCecCxMW52nD2" crossorigin="anonymous"></script>
<pre><?php echo $_SESSION['debugMeldung'];	$_SESSION['debugMeldung']='' ?></pre>	
</body>
</html>
