<!doctype html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">
  <meta name="generator" content="">
  <title>Beispiel</title>
  <link rel="Shortcut Icon" href="favicon.ico">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor" crossorigin="anonymous">
  <link rel="stylesheet" type="text/css" href="./css/screen.css">
  <style>
  </style>
</head>

<body>
  <div class="container mt-5 d-flex justify-content-center">
    <div class="col-12 col-sm-10 col-md-8 col-lg-7 col-xl-6 col-xxl-5 px-4" id="seite">
      <div class="kopf row">
        <div class="col-8 username">
          <span class="">
            <?php
              if (isset( $_SESSION['teilnehmer']) ) {
                echo $_SESSION['teilnehmer']['name'];
                echo '</span ><br><a href="index.php?s=login" id="logout">logout</a>';
              }
            ?>
          
        </div>
        <div class="col-4 logo">
          <img src="img/Logo.png" alt="Logo" width="100" class="float-end">
        </div>
      </div>
      <div class="row" id="meldung">
        <div class="col-lg-12 meldung">
          <hr class="mb-5">
          <div class="d-grid gap-2"> 
            <?php
            if ('' != $_SESSION['Meldung'] ) {
              echo '<div class="alert alert-danger" role="alert">' . $_SESSION['Meldung'] . '</div>';
              $_SESSION['Meldung'] = '';
            }
            ?>
          </div>
        </div>
      </div>