<div class="row">
  <div class="col-lg-12" >
  <form class="" action="index.php" method="GET">
        <input type="text" name="teilnehmer" value="" class="form-control my-3" placeholder="Teilnehmername">
        <input type="password" name="passwort" value="" class="form-control mb-3" placeholder="Passwort">
        <div class="d-grid gap-2">
          <button type="submit" class="btn btn-danger " name="login" >Enter</button>
        </div>
      </form>
  </div>
